name: dadata
description: DaData.ru Suggestions API implementation (address suggestions, reverse geocoding)
version: 0.3.3
repository: https://github.com/darkxanter/dadata_flutter

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  json_annotation: ^4.7.0
  http: ^0.13.5

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.21.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
